# RiskAI – Modelltraining und -vergleich

In dieser Phase trainieren wir verschiedene Machine-Learning-Modelle zur Erkennung von Kreditkartenbetrug.
Wir vergleichen:
1. Logistische Regression
2. Entscheidungsbäume
3. Random Forest (später)
4. Gradient Boosting / XGBoost (später)


In [18]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_curve, auc

X_train = pd.read_csv("../data/processed/X_train_scaled.csv")
X_test = pd.read_csv("../data/processed/X_test_scaled.csv")
y_train = pd.read_csv("../data/processed/y_train.csv").values.ravel()
y_test = pd.read_csv("../data/processed/y_test.csv").values.ravel()

print(f"Trainingsdaten: {X_train.shape} | Testdaten: {X_test.shape}")

Trainingsdaten: (226980, 32) | Testdaten: (56746, 32)


In [19]:
# 1. Baseline Logistische Regression (Standard, ohne Gewichtung)
lr_baseline = LogisticRegression(max_iter=1000, random_state=42)
lr_baseline.fit(X_train, y_train)

# 2. Logistische Regression mit ausbalancierten Klassengewichten
lr_balanced = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42)
lr_balanced.fit(X_train, y_train)


print("Beide logistischen Regressionsmodelle erfolgreich trainiert!")

Beide logistischen Regressionsmodelle erfolgreich trainiert!


In [20]:
# Wir vergleichen und bewerten jetzt unsere Modelle
y_pred_baseline = lr_baseline.predict(X_test)
y_pred_balanced = lr_balanced.predict(X_test)


print("=== BASELINE MODELL (Ohne Klassengewichte) ===")
print(classification_report(y_test, y_pred_baseline))
print("Konfusionsmatrix:")
print(confusion_matrix(y_test, y_pred_baseline))


print("=== BASELINE MODELL (Mit class_weight=balanced) ===")
print(classification_report(y_test, y_pred_balanced))
print("Konfusionsmatrix:")
print(confusion_matrix(y_test, y_pred_balanced))

=== BASELINE MODELL (Ohne Klassengewichte) ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.85      0.58      0.69        95

    accuracy                           1.00     56746
   macro avg       0.92      0.79      0.84     56746
weighted avg       1.00      1.00      1.00     56746

Konfusionsmatrix:
[[56641    10]
 [   40    55]]
=== BASELINE MODELL (Mit class_weight=balanced) ===
              precision    recall  f1-score   support

           0       1.00      0.97      0.99     56651
           1       0.06      0.87      0.10        95

    accuracy                           0.97     56746
   macro avg       0.53      0.92      0.55     56746
weighted avg       1.00      0.97      0.99     56746

Konfusionsmatrix:
[[55225  1426]
 [   12    83]]


## Entscheidungsbäume (Decision Trees)

Wir trainieren nun Entscheidungsbäume (Baseline und Balanced).
Um Overfitting zu verhindern, begrenzen wir die maximale Tiefe des Baumes auf `max_depth=5`.


In [21]:
dt_baseline = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_baseline.fit(X_train, y_train)

dt_balanced = DecisionTreeClassifier(max_depth=5, class_weight="balanced", random_state=42)
dt_balanced.fit(X_train, y_train)

print("Entscheidungsbäume erfolgreich trainiert.")

Entscheidungsbäume erfolgreich trainiert.


In [22]:
y_pred_dt_baseline = dt_baseline.predict(X_test)
y_pred_dt_balanced= dt_balanced.predict(X_test)

print("=== DECISION TREE BASELINE (Ohne Klassengewichte) ===")
print(classification_report(y_test, y_pred_dt_baseline))
print("Konfusionsmatrix:")
print(confusion_matrix(y_test, y_pred_dt_baseline))

print("\n=== DECISION TREE BALANCED (Mit class_weight='balanced') ===")
print(classification_report(y_test, y_pred_dt_balanced))
print("Konfusionsmatrix:")
print(confusion_matrix(y_test, y_pred_dt_balanced))

=== DECISION TREE BASELINE (Ohne Klassengewichte) ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.88      0.71      0.78        95

    accuracy                           1.00     56746
   macro avg       0.94      0.85      0.89     56746
weighted avg       1.00      1.00      1.00     56746

Konfusionsmatrix:
[[56642     9]
 [   28    67]]

=== DECISION TREE BALANCED (Mit class_weight='balanced') ===
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     56651
           1       0.04      0.85      0.07        95

    accuracy                           0.96     56746
   macro avg       0.52      0.91      0.53     56746
weighted avg       1.00      0.96      0.98     56746

Konfusionsmatrix:
[[54647  2004]
 [   14    81]]


## Random Forest Classifier

Wir trainieren nun einen Random Forest mit 100 Bäumen.
Um das Training auf deinem Mac zu beschleunigen, nutzen wir `n_jobs=-1` (nutzt alle verfügbaren CPU-Kerne parallel).


In [24]:
from sklearn.ensemble import RandomForestClassifier


rf_baseline = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)
rf_baseline.fit(X_train, y_train)

rf_balanced = RandomForestClassifier(n_estimators=100, max_depth=10, class_weight='balanced', random_state=42, n_jobs=-1)
rf_balanced.fit(X_train, y_train)

print("Random Forests erfolgreich trainiert!")


Random Forests erfolgreich trainiert!


In [25]:
y_pred_rf_baseline = rf_baseline.predict(X_test)
y_pred_rf_balanced = rf_balanced.predict(X_test)

print("=== RANDOM FOREST BASELINE (Ohne Klassengewichte) ===")
print(classification_report(y_test, y_pred_rf_baseline))
print("Konfusionsmatrix:")
print(confusion_matrix(y_test, y_pred_rf_baseline))

print("\n=== RANDOM FOREST BALANCED (Mit class_weight='balanced') ===")
print(classification_report(y_test, y_pred_rf_balanced))
print("Konfusionsmatrix:")
print(confusion_matrix(y_test, y_pred_rf_balanced))


=== RANDOM FOREST BASELINE (Ohne Klassengewichte) ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.97      0.73      0.83        95

    accuracy                           1.00     56746
   macro avg       0.99      0.86      0.92     56746
weighted avg       1.00      1.00      1.00     56746

Konfusionsmatrix:
[[56649     2]
 [   26    69]]

=== RANDOM FOREST BALANCED (Mit class_weight='balanced') ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.89      0.74      0.80        95

    accuracy                           1.00     56746
   macro avg       0.94      0.87      0.90     56746
weighted avg       1.00      1.00      1.00     56746

Konfusionsmatrix:
[[56642     9]
 [   25    70]]


## XGBoost Classifier (Gradient Boosting)

Wir implementieren nun XGBoost. 
Für die Gewichtung berechnen wir das genaue Verhältnis von legitimen Transaktionen zu Betrugsfällen (`scale_pos_weight`).


In [30]:
from xgboost import XGBClassifier

xgb_baseline = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1, n_jobs=-1)
xgb_baseline.fit(X_train, y_train)

ratio = len(y_train[y_train == 0] / len(y_train[y_train == 1]))

xgb_balanced = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1, scale_pos_weight=ratio, random_state=42, n_jobs=-1)
xgb_balanced.fit(X_train, y_train)

print(f"XGBoost Modelle erfolgreich trainiert! (Gewichtungsfaktor scale_pos_weight: {ratio:.2f})")

XGBoost Modelle erfolgreich trainiert! (Gewichtungsfaktor scale_pos_weight: 226602.00)


In [32]:

y_pred_xgb_baseline = xgb_baseline.predict(X_test)
y_pred_xgb_balanced = xgb_balanced.predict(X_test)

print("=== XGBOOST BASELINE (Ohne Klassengewichte) ===")
print(classification_report(y_test, y_pred_xgb_baseline))
print("Konfusionsmatrix:")
print(confusion_matrix(y_test, y_pred_xgb_baseline))

print("\n=== XGBOOST BALANCED (Mit scale_pos_weight) ===")
print(classification_report(y_test, y_pred_xgb_balanced))
print("Konfusionsmatrix:")
print(confusion_matrix(y_test, y_pred_xgb_balanced))


=== XGBOOST BASELINE (Ohne Klassengewichte) ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.95      0.73      0.82        95

    accuracy                           1.00     56746
   macro avg       0.97      0.86      0.91     56746
weighted avg       1.00      1.00      1.00     56746

Konfusionsmatrix:
[[56647     4]
 [   26    69]]

=== XGBOOST BALANCED (Mit scale_pos_weight) ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.22      0.82      0.35        95

    accuracy                           0.99     56746
   macro avg       0.61      0.91      0.67     56746
weighted avg       1.00      0.99      1.00     56746

Konfusionsmatrix:
[[56372   279]
 [   17    78]]
